server:
  port: 8081
  servlet:
    context-path: /pre-proposal

spring:
  datasource:
    url: jdbc:oracle:thin:@recdbq1.1dc.com:1521:RECQA?cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: PRE_PROPOSAL_SIT
    password: PPS#01923
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        show_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

fdsecurity:
  url: https://cat-webfarm.1dc.com/fd-security/permission-check

cors:
  enabled: true
  allowed-headers: "*"
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-origins: "*"
  exposed-headers: Content-Disposition, Content-Length, Content-Type

springdoc:
  swagger-ui:
    url: /v3/api-docs/
