#put specific configuration in this file
application:
  name: pre-proposal-api
  description: @project.description@
  version: @project.version@
  path.pkg: com.fiserv.preproposal.api
  jenkins.build.version: @build.number@

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO

fdsecurity:
  url: https://cat-webfarm.1dc.com/fd-security/permission-check

hibernate:
  show_sql: false

jdbc:
  driver-class-name: oracle.jdbc.driver.OracleDriver
  show-sql: true

spring:
  datasource:
    jndi-name: java:/jboss/datasources/ExampleDS
  jooq:
    sql-dialect: org.hibernate.dialect.Oracle10gDialect
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect

cors:
  enabled: true
  allowed-headers: "*"
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-origins: "*"
  exposed-headers: Content-Disposition, Content-Length, Content-Type