server:
  port: 8081
  servlet:
    context-path: /poc-hibernate-envers

spring:
  datasource:
    url: jdbc:oracle:thin:@recdbq1.1dc.com:1521:RECQA?cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: PRE_PROPOSAL_SIT
    password: PPS#01923
    driver-class-name: oracle.jdbc.OracleDriver

fdsecurity:
  url: https://cat-webfarm.1dc.com/fd-security/permission-check

cors:
  enabled: true
  allowed-headers: "*"
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-origins: "*"
  exposed-headers: Content-Disposition, Content-Length, Content-Type

springdoc:
  swagger-ui:
    url: /v3/api-docs/

logging:
  config: classpath:logs/log4j2-spring.dev.xml

management:
  endpoint:
    logfile:
      external-file: ./target/logs/${spring.application.name}.log

reports:
  temp-output: ./target/tmp/${spring.application.name}