#put specific configuration in this file
server:
  servlet:
    context-path: /pre-proposal-api

spring:
  profiles:
    active: @spring.profiles.active@

springdoc:
  show-actuator: true
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html

management:
  endpoint:
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /_monitor

layout: 'src/main/resources/io/cef/output/layout.xml'
