#put specific configuration in this file
application:
  name: pre-proposal-api
  description: @project.description@
  version: @project.version@
  path.pkg: com.fiserv.preproposal.api
  jenkins.build.version: @build.number@

spring:
  datasource:
    url: jdbc:oracle:thin:@recdbq1.1dc.com:1521:RECQA?cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: PRE_PROPOSAL_SIT
    password: PPS#01923
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    properties:
      hibernate:
        format_sql: false
        order_inserts: true
        show_sql: true
        use_sql_comments: true


#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

fdsecurity:
  url: https://cat-webfarm.1dc.com/fd-security/permission-check

cors:
  enabled: true
  allowed-headers: "*"
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-origins: "*"
  exposed-headers: Content-Disposition, Content-Length, Content-Type

springdoc:
  swagger-ui:
    url: /v3/api-docs/

logging:
  config: classpath:logs/log4j2-spring.sit.xml

management:
  endpoint:
    logfile:
      external-file: /appserver/logs/${spring.application.name}/${spring.application.name}.log