fdsecurity:
  url: https://sba-web.1dc.com/fd-security/permission-check

spring:
  datasource:
    jndi-name: java:/PRE_PROPOSAL_DS
    properties:
      hibernate:
        format_sql: false
        order_inserts: true
        show_sql: true
        use_sql_comments: true

cors:
  enabled: true
  allowed-headers: "*"
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-origins: "*"
  exposed-headers: Content-Disposition, Content-Length, Content-Type

logging:
  config: classpath:logs/log4j2-spring.prd.xml

management:
  endpoint:
    logfile:
      external-file: /appserver/logs/${spring.application.name}/${spring.application.name}.log

reports:
  temp-output: /appserver/tmp/${spring.application.name}