spring:
  application:
    name: pre-proposal-api
  profiles:
    active: @activeProfile@

springdoc:
  show-actuator: true
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: [ 'health', 'info', 'logfile' ]
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    logfile:
      enabled: true

org:
  jobrunr:
    background-job-server:
      enabled: true

reports:
  days-to-expire: 1