fdsecurity:
  url: https://cat-webfarm.1dc.com/fd-security/permission-check

spring:
  datasource:
    jndi-name: java:/PRE_PROPOSAL_DS

cors:
  enabled: true
  allowed-headers: "*"
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-origins: "*"
  exposed-headers: Content-Disposition, Content-Length, Content-Type

# configuracoes de logging
logging:
  config: classpath:logs/log4j2-spring.uat.xml

management:
  endpoint:
    logfile:
      external-file: /appserver/logs/${spring.application.name}/${spring.application.name}.log

reports:
  temp-output: /appserver/tmp/${spring.application.name}